### PR TITLE
Allow readonly properties

### PR DESCRIPTION
**Pull request by jakubvano**
Resolves https://github.com/icanzilb/JSONModel/issues/289

### CODE REVIEW

**Comment by dbachrach** [comment]
I think this is a pretty big breaking change. Read-only currently implies `Ignore`. I think you would need to still maintain this old behavior by default. Thoughts?

**Comment by infimache** [comment]
Yes, ofc. How did I not consider that.. However, I think that support for immutable model objects is something that `JSONModel` needs.

What do you think about syntax in the lines of:

```
@interface MyObject : JSONModel <ReadonlyPropertiesNotIgnoredByDefault>
//...
@end
```
Not sure about the protocol name though..

**Comment by dbachrach** [comment]
The protocol route could work. It's also worth adding `+ (BOOL)ignoresReadOnlyProperties`, which subclasses can override and return `YES`/`NO`. The default should be YES.

**Comment by infimache** [comment]
Agreed - protocol approach is nice for its declarativeness, while method approach might be preferable for those who do not want to abuse protocols.

**Comment by ssowonny** [comment]
This PR looks awesome!

**Comment by billinghamj** [comment]
Imo, the `+ (BOOL)ignoresReadOnlyProperties` is cleaner, and I'm pretty against supporting both.

**Comment by billinghamj** [comment]
Also what would happen when deserializing into a `readonly` property? Would it just skip the property?

**Comment by billinghamj** [comment]
There is also this alternative approach - https://github.com/icanzilb/JSONModel/issues/289#issuecomment-114126403

**Comment by jakubvano** [comment]
@billinghamj deserialising would fill readonly properties as well (skipping is current behaviour), point of this PR, is to enable having immutable serialisable objects. 
As I've mentioned above, going the protocol way is convenient if you want to clearly declare this behaviour in your `@interface`. But in practice I've found myself just creating `@interface AllowReadonliesJSONModel: JSONModel` and have my objects inherit from it.

However, as I am currently working almost exclusively in `Swift`, and given lack of response from `JSONModel` maintainers on this subject, I won't be working on this PR anymore. 
Feel free to fork it if you wanna continue.

**Comment by billinghamj** [comment]
@jakubvano I'm afraid that actually isn't possible. If a property is `readonly`, JSONModel cannot set the property - because there is no setter.

To be honest, because of how `readonly` properties work, JSONModel would behave strangely when deserializing anyway. The method of handling this mentioned in #289 is the only way it could work properly.

**Comment by jakubvano** [comment]
I don't get how is it not possible - in this PR I did it: `JSONModel` uses KVC for setting values of properties, and that works regardless of `readonly` modifier. In fact, during serialisation `JSONModel` is explicitly skipping properties with `readonly` modifier.
Well, this was true back in the July, maybe `JSONModel` changed the serialisation process since then (wasn't following much lately).

**Comment by billinghamj** [comment]
How would KVC set the property without there being a setter?

**Comment by faizan-carameltech** [comment]
What is the status on this? Till when can we expect serialisation support for readonly properties?

**Comment by billinghamj** [comment]
@faizan-carameltech `readonly` properties are implicitly considered to be the same as `Ignore` properties. At present, there are no plans to change this.

**Pull request closed without merging**
