### PR TITLE
Fix for not used JSONToModelKeyBlock

### PR DESCRIPTION
**Pull request by Slawek-XSolve**

### CODE REVIEW

**Comment by billinghamj** [comment]
@Slawek-XSolve Thanks for the PR. Please also add a test case which fails without this change, and passes with the change.

**Comment by icanzilb** [comment]
Hey @Slawek-XSolve can you add a test please? What problem is the PR solving?

**Comment by Slawek-XSolve** [comment]
Hey,

I will add tests and some explanation, after finishing current project.

Regards,
Slawek

**Comment by billinghamj** [comment]
@EliSchleifer We just need tests for this PR, then can fix it.

**Comment by billinghamj** [comment]
Okay going to close this - sorry. Can't accept a PR like this without tests.

**Comment by icanzilb** [comment]
👍 the library is so big now that accepting code without test coverage is not possible

**Comment by billinghamj** [comment]
The root cause of this is explained in #491

**Pull request closed without merging**
