### PR TITLE
skip property in recurse models

### PR DESCRIPTION
**Pull request by melvin7**
skip property in recurse models

### CODE REVIEW

**Comment by billinghamj** [comment]
Hi @melvin7 - thanks for your pull request.

I just need three things to get this sorted:

1. explanation and rationale for why the change should happen
2. unit tests covering this new functionality
3. rebase your changes into a single commit with a slightly more verbose commit message - include the rationale in there

**Comment by melvin7** [comment]
Thank you for you response .
In my App,there is a HTTP POST request need some user data.
one of the params is recurse models it has three levels models 

like this

`/**
 *  单篇小章节，由标题内容图片数据组成
 */
@protocol TFOImageModel;
@interface TFOSubContentModel : TimeFaceModel

@property (nonatomic ,copy) NSString *subtitle;
@property (nonatomic ,copy) NSString *content;
@property (nonatomic ,strong) NSMutableArray<TFOImageModel> *resource_list;

@end

/**
 *  用于一键成书的单篇文章，由主标题与章节数组组成
 */
@protocol TFOSubContentModel;
@interface TFOContentModel : TimeFaceModel

@property (nonatomic ,copy) NSString *title;
@property (nonatomic ,strong) NSMutableArray<TFOSubContentModel> *content_list;

@end `

the TFOImageModel has many property,some of them do not submit to the server.

**Comment by billinghamj** [comment]
Ah okay yes I understand. So this recurses the `toDictionaryWithKeys` parameter.

I'm not sure we'd necessarily want to support this directly, as the keys to use would probably depend on the specific Model - it wouldn't necessarily be relevant for all child properties.

**Comment by melvin7** [comment]
Sometimes a model has many properties.some properties may not post to sever. it will use in App.
In my App TFOImageModel has many properties ,such as imageWidth,imageHeight,imageURL,imageScale,imageRotation,imageRemark,imageDate...
when me  post TFOImageModel ,it needs imageWidth,imageHeight,imageURL.
It is normal.
JSONModel `toDictionaryWithKeys ` without considering  recurse model's properties

**Comment by billinghamj** [comment]
Indeed, but I'm afraid this method isn't one we're going to allow. You'd need to go with some other way of doing it, where the keys to include are explicitly defined for each different model.

**Pull request closed without merging**
